name: Trigger Repository Workflows

on:
  issues:
    types:
      - opened
      - edited

# expected issue body input should be structured as follows:
  #     {
  #         "rep01": {
  #             "repository": "rep01",
  #             "organisation": "org01"
  #         },
  #         "rep02": {
  #             "repository": "rep02",
  #             "organisation": "org02"
  #         } 
  #     }

jobs:
  trigger-repo-workflows:
    if: contains(github.event.issue.labels.*.name, 'settings-meets-standard1')
    runs-on: fixed-ip-runner-4core-22.04
    strategy:  
      matrix:
        repository: ${{ fromJson(github.event.issue.body).*.repository }}  # rep01, repo02
      max-parallel: 1
    steps:
      - name: Checkout Central Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_MIGRATION_PAT }}

      # Commenting the below lines to test out the settings-meet-standard yml. After testing this needs to be un-commented
      # - name: Trigger Runner Change Workflows in Other Repositories
      #   id: step-1
      #   run: |
      #       echo "Triggering workflow in ${{ matrix.repository }}"
      #       curl -X POST \
      #         -H "Accept: application/vnd.github+json" \
      #         -H "Authorization: Bearer ${{ secrets.GH_MIGRATION_PAT }}" \
      #         -H "X-GitHub-Api-Version: 2022-11-28" \
      #       https://api.github.com/repos/${{ fromJSON(github.event.issue.body)[matrix.repository].organisation }}/${{ matrix.repository }}/actions/workflows/replace-runner.yml/dispatches \
      #         -d '{
      #           "ref": "github-migration"
      #         }'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_MIGRATION_PAT }}

      # Commenting the below lines to test out the settings-meet-standard yml. After testing this needs to be un-commented
      # - name: Trigger Github Token Permissoin workflow in Remote Repository
      #   id: step-2
      #   run: |
      #       echo "Triggering workflow in ${{ matrix.repository }}"
      #       curl -X POST \
      #         -H "Accept: application/vnd.github+json" \
      #         -H "Authorization: Bearer ${{ secrets.GH_MIGRATION_PAT }}" \
      #         -H "X-GitHub-Api-Version: 2022-11-28" \
      #       https://api.github.com/repos/${{ fromJSON(github.event.issue.body)[matrix.repository].organisation }}/${{ matrix.repository }}/actions/workflows/token-permission.yml/dispatches \
      #         -d '{
      #           "ref": "github-migration"
      #         }'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_MIGRATION_PAT }}

      - name: Trigger Repository Settings Workflows in Other Repositories
        id: step-3
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_MIGRATION_PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: '${{ fromJSON(github.event.issue.body)[matrix.repository].organisation }}',
              repo: '${{ matrix.repository }}',
              workflow_id: 'settings-meet-standard.yml',
              ref: 'github-migration',
              inputs: {
                repository: '${{ matrix.repository }}',
                organisation: '${{ fromJSON(github.event.issue.body)[matrix.repository].organisation }}'
              }
            });
