name: Update Repository Teams

on:
  workflow_dispatch:

jobs:
  update-teams:
    runs-on: fixed-ip-runner-4core-22.04
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_MIGRATION_PAT }}
          path: ./source-repo

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Choose the Python version you need

      - name: Install Dependencies
        run: |
          python -m pip install -U pip
          pip install -r ${{ github.workspace }}/source-repo/requirements.txt  # You should have a requirements.txt file with your Python package dependencies

      # - name: Run Python Script for Testing Organization
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_MIGRATION_PAT}}
      #   run: python ${{ github.workspace }}/source-repo/files/Github_teams_update_Test.py

      - name: Run Python Script for Shared Organization
        env:
          GITHUB_TOKEN: ${{ secrets.GH_MIGRATION_PAT}}
        run: python ${{ github.workspace }}/source-repo/files/Github_teams_update_Shared.py  # Replace with the actual filename of your Python script

      - name: Run Python Script for Confidential Organization
        env:
          GITHUB_TOKEN: ${{ secrets.GH_MIGRATION_PAT }}
        run: python ${{ github.workspace }}/source-repo/files/Github_teams_update_Confidential.py

      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
          name: team-update-results
          path: ${{ github.workspace }}/source-repo/data/team_update*.csv
