name: Fetch GitHub Teams

on:
  workflow_dispatch:

jobs:
  fetch-teams:
    runs-on: fixed-ip-runner-4core-22.04
    env:
        GK_PAT: ${{ secrets.GH_MIGRATION_PAT }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_MIGRATION_PAT }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Dependencies
      run: |
        python -m pip install -U pip
        pip install requests openpyxl PyGithub

    - name: Fetch GitHub Teams and Members for Shared Org
      run: python files/fetch_teams_shared.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Fetch GitHub Teams and Members for Confidential Org
      run: python files/fetch_teams_confidential.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Report
      uses: actions/upload-artifact@v3
      with:
        name: team-fetch-results
        path: ${{ github.workspace }}/teams_and_members*.xlsx

    # - name: Import GPG key
    #   run: |
    #     echo "${GPG_PRIVATE_KEY}" | gpg --batch --import
    #   env: 
    #     GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

    # - name: List GPG key
    #   run: |
    #     gpg --list-secret-keys --keyid-format LONG
      
    # - name: Add the custom gpg siging program that passes the passphrase to the gpg CLI
    #   run: |
    #     rm -rf /tmp/gpg.sh
    #     echo '#!/bin/bash' >> /tmp/gpg.sh
    #     echo 'gpg --batch --pinentry-mode=loopback --passphrase $GPG_KEY_PASSPHRASE $@' >> /tmp/gpg.sh
    #     chmod +x /tmp/gpg.sh

    # - name: Setup git
    #   run: |
    #     git config commit.gpgsign true
    #     git config user.signingkey $GPG_KEY_ID
    #     git config gpg.program /tmp/gpg.sh
    #   env:
    #     GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}

    # - name: Commit Changes
    #   run: |
    #     git config user.email ${{ secrets.GIT_COMMITTER_EMAIL }}
    #     git config user.name ${{ secrets.GIT_COMMITTER_NAME }}
    #     git pull
    #     git add teams_and_members.xlsx
    #     git commit -m "Update teams and members file - $(date +"%Y-%m-%d %H:%M:%S")"
    #     git push    
    #   env:
    #     GPG_KEY_PASSPHRASE: ${{ secrets.PASSPHRASE }}
