#
name: Replace Bot User Name

on:
    workflow_dispatch:
    #inputs:
      #branch:
        #description: 'Target Branch'
        #required: true

jobs:
  replace-botuser:
    runs-on: fixed-ip-runner-4core-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
            token: ${{ secrets.GH_MIGRATION_PAT }}
            path: ./source-repo
   
      - name: Import GPG key
        run: |
          echo "${GPG_PRIVATE_KEY}" | gpg --batch --import
        env: 
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Add the custom gpg signing program that passes the passphrase to the gpg CLI
        run: |
          rm -rf /tmp/gpg.sh
          echo '#!/bin/bash' >> /tmp/gpg.sh
          echo 'gpg --batch --pinentry-mode=loopback --passphrase $GPG_KEY_PASSPHRASE $@' >> /tmp/gpg.sh
          chmod +x /tmp/gpg.sh

      - name: Setup git
        run: |
          git config --global user.email ${{ secrets.GIT_COMMITTER_EMAIL }}
          git config --global user.name ${{ secrets.GIT_COMMITTER_NAME }}
          git config --global commit.gpgsign true
          git config --global user.signingkey $GPG_KEY_ID
          git config --global gpg.program /tmp/gpg.sh
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}

      - name: Replace Bot User in Workflow Files
        run: |
          mapfile -t repositories < "${{ github.workspace }}/source-repo/repositories.txt"
          for repo in "${repositories[@]}"; do
              IFS='/' read -r org_name repo_name <<< "$repo"
              echo "Processing repository: $org_name/$repo_name"                       
          
              # Clone the repository
              git clone -b github-migration "https://${{ secrets.GH_MIGRATION_PAT }}@github.com/$repo.git" "./target-repo"
          
              # Check if .github folder exists
              github_folder="./target-repo/.github"
              if [ ! -d "$github_folder" ]; then
                echo "$repo_name;NA;.github folder does not exist" >> "${{ github.workspace }}/source-repo/replace_botuser_output.txt"
                continue
              else
                if find "./target-repo/.github" -type f \( -name "*.yaml" -o -name "*.yml" \) -print -quit | grep -q .; then
                    yaml_count=$(find "./target-repo/.github" -type f -name "*.yaml" | wc -l)
                    yml_count=$(find "./target-repo/.github" -type f -name "*.yml" | wc -l)
                    echo "Total count of YML files for repo $repo_name is: $yml_count"
                    echo "Total count of YAML files for repo $repo_name is: $yaml_count"
                fi

                # if [ "$yml_count" -eq 0 ]; then
                #   echo "$repo_name;NA;No YML files present" >> "${{ github.workspace }}/source-repo/replace_botuser_output.txt"
                # fi
                # if [ "$yaml_count" -eq 0 ]; then
                #   echo "$repo_name;NA;No YAML files present" >> "${{ github.workspace }}/source-repo/replace_botuser_output.txt"
                # fi

                # Iterate over .yml and .yaml files in .github folder
                for file in "./target-repo/.github"/*.yml; do
                  if [ -e "$file" ]; then
                     case "$(basename "$file")" in
                        secret-migration-environment.yml|secret-migration-repository.yml|call-env-secret.yml|call-rep-secret.yml|replace-string-org-only.yml|replace-string-org-repo.yml|replace-string-team-only.yml|replace-string-team-url.yml)
                            # Skip these files
                            ;;
                        *)                      
                            if grep -qi 'landg-platform-dotcom-machine-user' "$file";  then
                              sed -i 's/landg-platform-dotcom-machine-user/dotcom-github-user_landg/Ig' "$file"
                              echo "$repo_name;$file;Bot User Replaced Successfully" >> "${{ github.workspace }}/source-repo/replace_botuser_output.txt"
                            fi
                            ;;
                     esac
                  fi
                done
                for file in "./target-repo/.github"/*.yaml; do
                  if [ -e "$file" ]; then
                       case "$(basename "$file")" in
                          secret-migration-environment.yml|secret-migration-repository.yml|call-env-secret.yml|call-rep-secret.yml|replace-string-org-only.yml|replace-string-org-repo.yml|replace-string-team-only.yml|replace-string-team-url.yml)
                              # Skip these filess
                              ;;
                          *)
                              if grep -qi 'landg-platform-dotcom-machine-user' "$file"; then
                                sed -i 's/landg-platform-dotcom-machine-user/dotcom-github-user_landg/Ig' "$file"
                                echo "$repo_name;$file;Bot User Replaced Successfully" >> "${{ github.workspace }}/source-repo/replace_botuser_output.txt"
                              fi
                              ;;
                       esac
                  fi
                done
              fi
              cd "./target-repo"

              if [ -n "$(git status --porcelain)" ]; then
                git add .
                git commit -S -m "Replace Bot User - $(date +"%Y-%m-%d %H:%M:%S")"
                git push origin github-migration
              else
                echo "$repo_name;NA;String Not Found" >> "${{ github.workspace }}/source-repo/replace_botuser_output.txt"
              fi
              cd ..
              rm -rf "./target-repo"
          done
        env:
            GPG_KEY_PASSPHRASE: ${{ secrets.PASSPHRASE }}
        
      - name: Upload bot user change report as artifact
        uses: actions/upload-artifact@v4
        with:
            name: botuser-change-report
            path: ${{ github.workspace }}/source-repo
